# Site settings
title: 居·宅·❤
SEOTitle: 居·宅 | ZYL_❤ Blog
header-img: img/cover-cute-daylight-1698482.jpg
email: 491723719@qq.com
description: "Battle and kill the monster."
keyword: "Dragon Uno  Blog"
url: "http://uufishtxl.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/uufishtxl/uufishtxl.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Give up? Not today!"
sidebar-avatar: /img/profile_picture.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     uufishtxl
github_username:    uufishtxl
facebook_username:  xiaoli.tang.393
twitter_username:   uufishtxl




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
  - jekyll-paginate



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge



# 评论系统
# Disqus（https://disqus.com/）
# disqus_shortname: uufishtxl

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 85d39cdf13a045a43f5e                            #生成的clientID
  clientSecret: e14f259dfd990a9be6092ae68cd86d08d721801d    #生成的clientSecret
  repo: uufishtxl.github.io    #仓库名称
  owner: uufishtxl    #github用户名
  admin: uufishtxl
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings

# Google Analytics
ga_track_id: 'UA-143508831-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Tom Johnson",
        href: "https://idratherbewriting.com/"
    }
]

topnav_title: Tutorials and Notes
# this appears on the top navigation bar next to the home button

github_editme_path: "uufishtxl/uufishtxl.github.io/blob/master/"
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

feedback_subject_line: Tutorials and Notes

feedback_email: edith1984@126.com
# used as a contact email for the Feedback link in the top navigation bar

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# feedback_link: "http://helpy.io/"
# if you uncomment the previous line, it changes where the feedback link points to

defaults:
  -
    scope:
      path: "pages/api_docs"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: api_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/frontEnd"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: frontEnd_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/vue"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: vue_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/dita"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: dita_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/osd"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: osd_s2721dgf_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/love_cholera"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: reading_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/cnet"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: cnet_sidebar
      topnav: topnav

  -
    scope:
      path: "pages/prdpjd"
      type: "pages"
    values:
      layout: "note_tutorial"
      search: true
      sidebar: pp_sidebar
      topnav: topnav